//! Single source of truth for the search filters and the exclusion settings,
//! both of which are built from these lists so they cannot drift apart.

/// `(id, title)`. Fallback when the live list cannot be fetched.
pub const GENRES: &[(&str, &str)] = &[
	("action", "Action"),
	("adventure", "Adventure"),
	("comedy", "Comedy"),
	("cooking", "Cooking"),
	("doujinshi", "Doujinshi"),
	("drama", "Drama"),
	("ecchi", "Ecchi"),
	("fantasy", "Fantasy"),
	("gender_bender", "Gender Bender"),
	("harem", "Harem"),
	("historical", "Historical"),
	("horror", "Horror"),
	("isekai", "Isekai"),
	("josei", "Josei"),
	("magic", "Magic"),
	("martial_arts", "Martial Arts"),
	("mature", "Mature"),
	("mecha", "Mecha"),
	("medical", "Medical"),
	("military", "Military"),
	("music", "Music"),
	("mystery", "Mystery"),
	("psychological", "Psychological"),
	("romance", "Romance"),
	("school_life", "School Life"),
	("sci_fi", "Sci-Fi"),
	("seinen", "Seinen"),
	("shoujo", "Shoujo"),
	("shounen", "Shounen"),
	("slice_of_life", "Slice of Life"),
	("smut", "Smut"),
	("sports", "Sports"),
	("supernatural", "Supernatural"),
	("thriller", "Thriller"),
	("tragedy", "Tragedy"),
	("webtoon", "Webtoon"),
	("yaoi", "Yaoi"),
	("yuri", "Yuri"),
];

/// `(id, title)`. Also used to split formats out of the live genre list, which
/// the site serves as one combined group.
pub const FORMATS: &[(&str, &str)] = &[
	("4_koma", "4 Koma"),
	("adaptation", "Adaptation"),
	("anthology", "Anthology"),
	("award_winning", "Award Winning"),
	("doujinshi", "Doujinshi"),
	("fan_colored", "Fan Colored"),
	("full_color", "Full Color"),
	("long_strip", "Long Strip"),
	("official_colored", "Official Colored"),
	("oneshot", "Oneshot"),
	("web_comic", "Web Comic"),
	("webtoon", "Webtoon"),
];
